#!/bin/sh

set -e

rm -rf config

mkdir -p config/task-lists config/package-lists

add_task ()
{
	local pass="$1"
	shift
	local task

	for task; do
		echo "$task" >> "config/task-lists/livecd-rootfs.chroot_$pass.list"
	done
}

add_package ()
{
	local pass="$1"
	shift
	local pkg

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.chroot_$pass.list"
	done
}

OPTS=
BINARY_IMAGES=iso
BOOT_LOADER=grub2
INITRAMFS=live-boot
INITRAMFS_COMPRESSION=lzma
INSTALLER=true

add_task install minimal standard

add_package live # lupin-casper

if [ -n "$APT_HTTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-http-proxy $APT_HTTP_PROXY"
fi
if [ -n "$APT_FTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-ftp-proxy $APT_FTP_PROXY"
fi

if [ -n "$SDK_CHROOTSHELL" ]; then
	OPTS="${OPTS:+$OPTS } --interactive shell"
fi

lb config noauto \
        --mode ubuntu \
        --distribution "oneiric" \
        --architecture i386 \
        --archive-areas "main restricted universe multiverse" \
        --bootstrap-keyring ubuntu-keyring \
        --binary-images "$BINARY_IMAGES" \
        --bootloader "$BOOT_LOADER" \
        --memtest none \
        --package-lists none \
        --security true \
        --initsystem none \
        --initramfs "$INITRAMFS" \
        --initramfs-compression "$INITRAMFS_COMPRESSION" \
        --linux-packages linux \
        --binary-filesystem fat32 \
        --username xbmc \
        --hostname XBMCLive \
        --iso-application XBMC_Live \
        --iso-volume XBMC_Live \
        --iso-publisher "http://xbmc.org" \
        --debian-installer "$INSTALLER" \
        --debian-installer-preseedfile preseed.cfg \
        --debian-installer-distribution "oneiric" \
        --debian-installer-gui disabled \
        --win32-loader disabled \
        "${@}"

# Copy additional config files to config tree
cp -R Files/config/* config
