#!/bin/sh

set -e

rm -rf config

mkdir -p config/task-lists config/package-lists

add_task ()
{
	local pass="$1"
	shift
	local task

	for task; do
		echo "$task" >> "config/task-lists/livecd-rootfs.chroot_$pass.list"
	done
}
add_package ()
{
	local pass="$1"
	shift
	local pkg

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.chroot_$pass.list"
	done
}

OPTS=
BINARY_IMAGES=iso-hybrid
BOOT_LOADER=syslinux
#BINARY_IMAGES=iso
#BINARY_IMAGES=usb
#BOOT_LOADER=syslinux

add_task install minimal standard

add_package live # lupin-casper

#	ubuntu-core)
#		OPTS="${OPTS:+$OPTS }--bootstrap-flavour=minimal"
#		OPTS="${OPTS:+$OPTS }--linux-packages=none"
#		KERNEL_FLAVOURS=none
#		BINARY_REMOVE_LINUX=false
#		;;

if [ -n "$APT_HTTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-http-proxy $APT_HTTP_PROXY"
fi
if [ -n "$APT_FTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-ftp-proxy $APT_FTP_PROXY"
fi

if [ -n "$SDK_CHROOTSHELL" ]; then
	OPTS="${OPTS:+$OPTS } --interactive shell"
fi

lb config noauto \
        --archive-areas "main restricted universe multiverse" \
        --distribution "oneiric" \
        --architecture i386 \
        --bootstrap-keyring ubuntu-keyring \
        --mirror-bootstrap "http://archive.ubuntu.com/ubuntu/" \
        --mirror-chroot "http://archive.ubuntu.com/ubuntu/" \
        --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
        --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
        --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
        --debian-installer-distribution "oneiric" \
        --package-lists none \
        --mode ubuntu \
        --cache disabled \
        --security true \
        --username xbmc \
        --binary-images "$BINARY_IMAGES" \
        --binary-filesystem fat32 \
        --hostname XBMCLive \
        --iso-application XBMC_Live \
        --iso-volume XBMC_Live \
        --iso-publisher "http://xbmc.org" \
        --linux-packages linux \
        --win32-loader disabled \
        --memtest none \
        --tasks minimal \
        --initsystem none \
        --debian-installer false \
        --debian-installer-preseedfile preseed.cfg \
        --debian-installer-gui disabled \
        --initramfs live-boot \
        --bootloader "$BOOT_LOADER" \
        "${@}"

# Copy additional config files to config tree
cp -R Files/config/* config
